### ISSUE TITLE
Close, cancel or something else to channel

### ISSUE THREAD

**Issue by fdabrao** [clojurewerkz/meltdown#11]
Hello,

What do I need to do after using channel? Close, cancel or what? In my program I restart the system if some fatal error happen. So, how to I dispose the used channel?

Best Regards

**Comment by michaelklishin** [comment]
Close it.

**Comment by fdabrao** [comment]
Can you please show me how?

**Comment by ifesdjeen** [comment]
Just call `(.close channel)` on the channel.
